"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import styles from "./welcome.module.css";

export default function WelcomePage() {
  const [modalOpen, setModalOpen] = useState(false);
  const [accepted, setAccepted] = useState(false);
  const router = useRouter();

  function handleAccept() {
    router.push("/onboarding");
  }

  return (
    <main className={styles.page}>
      <div className={styles.content}>
        <img src="/img/logo.svg" alt="DIMA Risk" className={styles.logo} />

        <h1 className={styles.heading}>
          Welcome to <span className={styles.accent}>DIMA Risk</span>
        </h1>
        <p className={styles.subheading}>
          Your AI-powered risk intelligence platform is ready to be configured.
          <br />
          We'll run a background scan and collect a few details about your
          organization — then your live dashboard will be ready.
        </p>

        <div className={styles.pillars}>
          <div className={styles.pillar}>
            <span className={styles.pillarIcon}>⚙</span>
            <h3 className={styles.pillarTitle}>Background Scan</h3>
            <p className={styles.pillarText}>
              Our AI engine scans your environment while you answer a few
              quick questions.
            </p>
          </div>
          <div className={styles.pillar}>
            <span className={styles.pillarIcon}>◈</span>
            <h3 className={styles.pillarTitle}>Risk Profiling</h3>
            <p className={styles.pillarText}>
              We build your organization's risk profile across cyber,
              compliance, and operational domains.
            </p>
          </div>
          <div className={styles.pillar}>
            <span className={styles.pillarIcon}>▣</span>
            <h3 className={styles.pillarTitle}>Live Dashboard</h3>
            <p className={styles.pillarText}>
              Results are stored and surfaced the moment your scan
              completes — no waiting required.
            </p>
          </div>
        </div>

        <button
          className={styles.ctaButton}
          onClick={() => setModalOpen(true)}
        >
          Get Started
        </button>
        <p className={styles.timeHint}>Takes about 5 minutes</p>
      </div>

      {modalOpen && (
        <div
          className={styles.overlay}
          onClick={(e) => e.target === e.currentTarget && setModalOpen(false)}
        >
          <div className={styles.modal} role="dialog" aria-modal="true">
            <h2 className={styles.modalTitle}>
              Terms of Use &amp; Data Processing Agreement
            </h2>

            <div className={styles.legalScroll}>
              <p className={styles.legalSection}>
                <strong>1. Scope of Use</strong>
                <br />
                This platform ("DIMA Risk") is provided exclusively to
                authorized enterprise clients for internal risk intelligence
                purposes. Access is non-transferable. You agree not to share
                credentials, reverse-engineer, or replicate any part of the
                platform without prior written consent from DIMA Risk Inc.
              </p>

              <p className={styles.legalSection}>
                <strong>2. Data Collection &amp; Processing</strong>
                <br />
                By proceeding, you authorize DIMA Risk to collect, process,
                and store organizational data submitted through this platform,
                including but not limited to: company metadata, infrastructure
                scope identifiers, compliance posture inputs, and scan
                telemetry. All data is encrypted at rest and in transit using
                AES-256 and TLS 1.3 respectively. Data is retained for the
                duration of your subscription and deleted within 30 days of
                account termination unless otherwise required by law.
              </p>

              <p className={styles.legalSection}>
                <strong>3. AI &amp; Machine Learning Disclaimer</strong>
                <br />
                Risk scores, anomaly flags, and recommendations generated by
                DIMA Risk are produced by AI and ML models and are{" "}
                <em>advisory in nature only</em>. They do not constitute legal,
                financial, or professional security advice. DIMA Risk Inc. does
                not guarantee the completeness or accuracy of model outputs.
                You remain solely responsible for decisions made based on
                platform results.
              </p>

              <p className={styles.legalSection}>
                <strong>4. Confidentiality</strong>
                <br />
                All data you submit is treated as confidential and is not sold,
                shared, or disclosed to third parties except where required by
                applicable law or regulatory authority. DIMA Risk staff access
                to client data is role-based, logged, and audited.
              </p>

              <p className={styles.legalSection}>
                <strong>5. Limitation of Liability</strong>
                <br />
                To the maximum extent permitted by law, DIMA Risk Inc. shall
                not be liable for any indirect, incidental, special, or
                consequential damages arising from your use of the platform,
                including data loss, business interruption, or security
                incidents occurring independently of platform operations.
                Aggregate liability shall not exceed the fees paid by you in
                the 12 months preceding the claim.
              </p>

              <p className={styles.legalSection}>
                <strong>6. Governing Law</strong>
                <br />
                This agreement is governed by the laws of the Province of
                British Columbia, Canada, without regard to conflict of law
                principles. Any disputes shall be resolved by binding
                arbitration in Vancouver, BC.
              </p>

              <p className={styles.legalSection}>
                <strong>7. Amendments</strong>
                <br />
                DIMA Risk Inc. reserves the right to update these terms at any
                time. Continued use of the platform following notification of
                changes constitutes acceptance of the revised terms.
              </p>
            </div>

            <label className={styles.checkboxRow}>
              <input
                type="checkbox"
                className={styles.checkbox}
                checked={accepted}
                onChange={(e) => setAccepted(e.target.checked)}
              />
              <span>
                I have read and agree to the Terms of Use and Data Processing
                Agreement above.
              </span>
            </label>

            <div className={styles.modalActions}>
              <button
                className={styles.declineButton}
                onClick={() => {
                  setModalOpen(false);
                  setAccepted(false);
                }}
              >
                Decline
              </button>
              <button
                className={styles.acceptButton}
                disabled={!accepted}
                onClick={handleAccept}
              >
                Accept &amp; Continue
              </button>
            </div>
          </div>
        </div>
      )}
    </main>
  );
}
